name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  create:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - perl-version: '5.30'
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'ci-dist: target-setup-perl'
        uses: PDLPorters/devops/github-actions/ci-dist@fix-macos
        with:
          target-setup-perl: true
          perl-version: ${{ matrix.perl-version }}
      - name: Install PDL dependencies
        uses: PDLPorters/devops/github-actions/install-dep-pdl-dep@master
      - name: Install LAPACK
        uses: PDLPorters/devops/github-actions/install-dep-lapack@fix-macos
      - name: 'ci-dist: target-all'
        uses: PDLPorters/devops/github-actions/ci-dist@fix-macos
        with:
          target-setup-perl: false
          target-install-dist-perl-deps: true
          dist-perl-deps-configure: PDL Devel::CheckLib ExtUtils::F77
          target-test-release-testing: true
          target-test: true
          test-enable-release-testing: ${{ matrix.release-test }}
          test-enable-coverage: ${{ matrix.coverage }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
